apiVersion: v1
kind: Service
metadata:
  name: research-backend-service
  labels:
    app: research-backend
spec:
  type: LoadBalancer
  selector:
    app: research-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
